### ISSUE TITLE
Worldguard and remove-attached-blocks

### ISSUE THREAD

**Issue by airwulf1** [turt2live/AntiShare#138]
Hi Turt,

When you put "remove-attached-blocks" to true it will remove attached items to blocks signs as frames. This is a good thing.

However in Worldguard regions you can grief very easily this way. An example.
1. Make a block with a frame attached.
2. Protect it and dont give yourself permission.
3. Try to remove the block in survival.
4. The block will disappear and quickly reappear because you don't have permission.
5. The item-frame will now be destroyed though.

Regards,
Airwulf1

**Comment by turt2live** [comment]
Closing due to this project no longer being maintained.
